# Generated by Django 5.0.14 on 2026-02-23 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el registro', verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='Fecha de modificación')),
                ('codigo', models.CharField(help_text='Código único de la planta (ej: PLT-001)', max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre de la planta', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada de la planta', verbose_name='Descripción')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('estado_provincia', models.CharField(blank=True, max_length=100, verbose_name='Estado/Provincia')),
                ('codigo_postal', models.CharField(blank=True, max_length=20, verbose_name='Código Postal')),
                ('pais', models.CharField(default='México', max_length=100, verbose_name='País')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitud')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la planta está activa', verbose_name='Activa')),
                ('imagen', models.ImageField(blank=True, help_text='Imagen o foto de la planta', null=True, upload_to='plantas/', verbose_name='Imagen')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Planta',
                'verbose_name_plural': 'Plantas',
                'ordering': ['codigo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el registro', verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='Fecha de modificación')),
                ('codigo', models.CharField(help_text='Código del nivel (ej: N1, PISO-1)', max_length=20, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del nivel', max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('numero_nivel', models.IntegerField(default=0, help_text='Número del nivel (0 = planta baja, negativos = sótanos)', verbose_name='Número de nivel')),
                ('altura', models.DecimalField(blank=True, decimal_places=2, help_text='Altura del nivel en metros', max_digits=6, null=True, verbose_name='Altura (m)')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('plano', models.ImageField(blank=True, help_text='Plano arquitectónico del nivel', null=True, upload_to='planos/niveles/', verbose_name='Plano')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveles', to='organizacion.planta', verbose_name='Planta')),
            ],
            options={
                'verbose_name': 'Nivel',
                'verbose_name_plural': 'Niveles',
                'ordering': ['planta', 'numero_nivel', 'codigo'],
                'unique_together': {('planta', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el registro', verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='Fecha de modificación')),
                ('codigo', models.CharField(help_text='Código único del responsable', max_length=20, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('INTERNO', 'Interno'), ('EXTERNO', 'Externo'), ('CONTRATISTA', 'Contratista')], default='INTERNO', max_length=20, verbose_name='Tipo')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('puesto', models.CharField(blank=True, max_length=100, verbose_name='Puesto')),
                ('departamento', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('telefono_movil', models.CharField(blank=True, max_length=50, verbose_name='Teléfono móvil')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha de ingreso')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='responsables/', verbose_name='Foto')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsable', to=settings.AUTH_USER_MODEL, verbose_name='Usuario del sistema')),
            ],
            options={
                'verbose_name': 'Responsable',
                'verbose_name_plural': 'Responsables',
                'ordering': ['apellidos', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el registro', verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='Fecha de modificación')),
                ('codigo', models.CharField(help_text='Código del área (ej: PROD-01, MANT)', max_length=20, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo_area', models.CharField(choices=[('PRODUCCION', 'Producción'), ('ALMACEN', 'Almacén'), ('MANTENIMIENTO', 'Mantenimiento'), ('CALIDAD', 'Calidad'), ('LABORATORIO', 'Laboratorio'), ('OFICINA', 'Oficina'), ('SEGURIDAD', 'Seguridad'), ('LOGISTICA', 'Logística'), ('OTRO', 'Otro')], default='PRODUCCION', max_length=50, verbose_name='Tipo de área')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('plano', models.ImageField(blank=True, null=True, upload_to='planos/areas/', verbose_name='Plano')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='organizacion.nivel', verbose_name='Nivel')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas_supervisadas', to='organizacion.responsable', verbose_name='Supervisor')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'ordering': ['nivel__planta', 'nivel', 'codigo'],
                'unique_together': {('nivel', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el registro', verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='Fecha de modificación')),
                ('codigo', models.CharField(help_text='Código de la subárea', max_length=20, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subareas', to='organizacion.area', verbose_name='Área')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subareas_responsable', to='organizacion.responsable', verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Subárea',
                'verbose_name_plural': 'Subáreas',
                'ordering': ['area', 'codigo'],
                'unique_together': {('area', 'codigo')},
            },
        ),
    ]
