# Generated by Django 5.0.14 on 2026-02-23 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text='Identificador único de la configuración', max_length=100, unique=True, verbose_name='Clave')),
                ('valor', models.TextField(help_text='Valor de la configuración', verbose_name='Valor')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('string', 'Texto'), ('int', 'Entero'), ('float', 'Decimal'), ('bool', 'Booleano'), ('json', 'JSON')], default='string', max_length=20, verbose_name='Tipo de dato')),
                ('editable', models.BooleanField(default=True, help_text='Si puede ser modificado desde la interfaz', verbose_name='Editable')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='HistorialCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del cambio', verbose_name='Fecha y hora')),
                ('tipo_operacion', models.CharField(choices=[('CREAR', 'Creación'), ('MODIFICAR', 'Modificación'), ('ELIMINAR', 'Eliminación'), ('CONSULTAR', 'Consulta'), ('ESTADO', 'Cambio de Estado'), ('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión')], help_text='Tipo de operación realizada', max_length=20, verbose_name='Tipo de operación')),
                ('modelo', models.CharField(help_text='Nombre del modelo que fue modificado', max_length=100, verbose_name='Modelo afectado')),
                ('objeto_id', models.CharField(help_text='Identificador del objeto afectado', max_length=50, verbose_name='ID del objeto')),
                ('objeto_repr', models.CharField(blank=True, help_text='Representación legible del objeto', max_length=255, verbose_name='Representación del objeto')),
                ('datos_anteriores', models.JSONField(blank=True, help_text='Datos del objeto antes del cambio (JSON)', null=True, verbose_name='Datos anteriores')),
                ('datos_nuevos', models.JSONField(blank=True, help_text='Datos del objeto después del cambio (JSON)', null=True, verbose_name='Datos nuevos')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se realizó la operación', null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, help_text='Información del navegador/cliente', verbose_name='User Agent')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional del cambio', verbose_name='Descripción')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que realizó la operación', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Cambio',
                'verbose_name_plural': 'Historial de Cambios',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['-fecha_hora'], name='core_histor_fecha_h_e47493_idx'), models.Index(fields=['modelo', 'tipo_operacion'], name='core_histor_modelo_898ee2_idx'), models.Index(fields=['usuario'], name='core_histor_usuario_cdd843_idx')],
            },
        ),
    ]
