# Generated by Django 5.0.14 on 2026-02-23 02:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0001_initial'),
        ('organizacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el registro', verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='Fecha de modificación')),
                ('tipo', models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo'), ('PREDICTIVO', 'Predictivo'), ('MEJORA', 'Mejora'), ('INSPECCION', 'Inspección'), ('CALIBRACION', 'Calibración'), ('LIMPIEZA', 'Limpieza'), ('OTRO', 'Otro')], default='PREVENTIVO', max_length=20, verbose_name='Tipo de mantenimiento')),
                ('codigo', models.CharField(blank=True, help_text='Código interno del mantenimiento', max_length=50, verbose_name='Código')),
                ('fecha', models.DateField(verbose_name='Fecha programada')),
                ('fecha_realizacion', models.DateField(blank=True, null=True, verbose_name='Fecha de realización')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En progreso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado'), ('POSPUESTO', 'Pospuesto')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=20, verbose_name='Prioridad')),
                ('descripcion', models.TextField(help_text='Descripción detallada del mantenimiento a realizar', verbose_name='Descripción del trabajo')),
                ('trabajo_realizado', models.TextField(blank=True, help_text='Descripción del trabajo efectivamente realizado', verbose_name='Trabajo realizado')),
                ('costo_mano_obra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo de mano de obra')),
                ('costo_repuestos', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo de repuestos')),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo total')),
                ('moneda', models.CharField(choices=[('BOB', 'Boliviano'), ('USD', 'Dólar Americano'), ('EUR', 'Euro')], default='BOB', max_length=3, verbose_name='Moneda')),
                ('tiempo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tiempo estimado (horas)')),
                ('tiempo_real', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Tiempo real (horas)')),
                ('resultado', models.CharField(choices=[('EXITOSO', 'Exitoso'), ('PARCIAL', 'Parcial'), ('FALLIDO', 'Fallido'), ('PENDIENTE', 'Pendiente')], default='PENDIENTE', max_length=20, verbose_name='Resultado')),
                ('evidencia_fotografica', models.ImageField(blank=True, null=True, upload_to='mantenimientos/evidencias/', verbose_name='Evidencia fotográfica')),
                ('documento', models.FileField(blank=True, null=True, upload_to='mantenimientos/documentos/', verbose_name='Documento adjunto')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('recomendaciones', models.TextField(blank=True, help_text='Recomendaciones para futuros mantenimientos', verbose_name='Recomendaciones')),
                ('proximo_mantenimiento', models.DateField(blank=True, null=True, verbose_name='Próximo mantenimiento')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='activos.activo', verbose_name='Activo')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_realizados', to='organizacion.responsable', verbose_name='Realizado por')),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_solicitados', to='organizacion.responsable', verbose_name='Solicitado por')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-fecha', '-creado'],
            },
        ),
        migrations.CreateModel(
            name='RepuestoUtilizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el registro', verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='Fecha de modificación')),
                ('codigo', models.CharField(blank=True, max_length=50, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad')),
                ('unidad', models.CharField(choices=[('pza', 'Pieza'), ('kg', 'Kilogramo'), ('lt', 'Litro'), ('m', 'Metro'), ('m2', 'Metro cuadrado'), ('m3', 'Metro cúbico'), ('par', 'Par'), ('jgo', 'Juego'), ('otro', 'Otro')], default='pza', max_length=20, verbose_name='Unidad')),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo unitario')),
                ('costo_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo total')),
                ('proveedor', models.CharField(blank=True, max_length=150, verbose_name='Proveedor')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('mantenimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='mantenimiento.mantenimiento', verbose_name='Mantenimiento')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Repuesto Utilizado',
                'verbose_name_plural': 'Repuestos Utilizados',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se creó el registro', verbose_name='Fecha de creación')),
                ('modificado', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación', verbose_name='Fecha de modificación')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('color', models.CharField(choices=[('green', 'Verde'), ('blue', 'Azul'), ('yellow', 'Amarillo'), ('orange', 'Naranja'), ('red', 'Rojo'), ('gray', 'Gris'), ('purple', 'Morado')], default='blue', max_length=20, verbose_name='Color')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creado_por', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modificado_por', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Tipo de Mantenimiento',
                'verbose_name_plural': 'Tipos de Mantenimiento',
                'ordering': ['codigo', 'nombre'],
            },
        ),
    ]
